<a href="https://colab.research.google.com/github/Pranav210905/NumPy/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4],
   [5,3,5,9],
   [8,6,4,1],
   [1,5,8,3]])

In [3]:
b=np.array([[1,4,1,6],
   [9,3,7,4],
   [4,3,3,2],
   [6,3,5,0]])

In [4]:
np.add(a,b)

array([[ 2,  6,  4, 10],
       [14,  6, 12, 13],
       [12,  9,  7,  3],
       [ 7,  8, 13,  3]])

In [5]:
np.subtract(a,b)

array([[ 0, -2,  2, -2],
       [-4,  0, -2,  5],
       [ 4,  3,  1, -1],
       [-5,  2,  3,  3]])

In [6]:
np.dot(a,b)

array([[ 55,  31,  44,  20],
       [106,  71,  86,  52],
       [ 84,  65,  67,  80],
       [ 96,  52,  75,  42]])

In [7]:
a.T

array([[1, 5, 8, 1],
       [2, 3, 6, 5],
       [3, 5, 4, 8],
       [4, 9, 1, 3]])

In [8]:
np.linalg.det(a)

-305.00000000000006

In [9]:
np.linalg.inv(a)

array([[-0.65245902,  0.26557377,  0.03278689,  0.06229508],
       [ 1.45901639, -0.57377049,  0.21311475, -0.29508197],
       [-0.99016393,  0.33770492, -0.13114754,  0.35081967],
       [ 0.42622951, -0.03278689, -0.01639344, -0.13114754]])

In [10]:
c=np.array([[2,1],[1,3]])
np.linalg.matrix_rank(c)

2

In [11]:
np.linalg.matrix_rank(a)

4

In [12]:
np.linalg.eig(a)

EigResult(eigenvalues=array([17.15147346+0.j        , -2.69594662+4.01785143j,
       -2.69594662-4.01785143j, -0.75958022+0.j        ]), eigenvectors=array([[-0.29989893+0.j        ,  0.20243781-0.07604802j,
         0.20243781+0.07604802j,  0.30293226+0.j        ],
       [-0.61743666+0.j        ,  0.40060875-0.39521081j,
         0.40060875+0.39521081j, -0.79207224+0.j        ],
       [-0.50397862+0.j        , -0.62432249+0.j        ,
        -0.62432249-0.j        ,  0.51531521+0.j        ],
       [-0.52425009+0.j        ,  0.15727507+0.47121402j,
         0.15727507-0.47121402j, -0.12370869+0.j        ]]))