<a href="https://colab.research.google.com/github/Pranav210905/NumPy/blob/main/Numpy_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Welcome to the NumPy practice exercise! Please follow these instructions carefully to complete your assignment:

1. **Read Each Question Carefully**: Each question is designed to test different aspects of your NumPy skills. Make sure to understand what is being asked before you start coding.

2. **Write Your Code in the Provided Cells**: For each question, you will find a corresponding code cell where you should write your solution. Do not modify any other part of the notebook.

3. **Run Your Code**: After writing your code, run the cell to ensure that your solution works as expected. Check the output and make sure it meets the requirements specified in the question.

4. **Complete All Questions**: Make sure you answer all the questions provided. Each question has been included to assess a different skill or concept in NumPy.

5. **Download Your Notebook**: Once you have completed all questions and verified that your solutions are correct, download your notebook file (.ipynb). You can do this by selecting `File > Download > Download .ipynb` from the menu.

6. **Submit Your Work**: Upload the downloaded `.ipynb` file to the designated learning platform for submission.

7. **Check Your Submission**: Ensure that you have submitted the correct file and that it is not corrupted. If there are any issues with the file, you may need to resubmit.

Good luck, and happy coding!

Q1. Import Numpy as `np`

In [1]:
import numpy as np

Q.2 Create a 5x5 array, with numbers ranging from 1-25 and save it in `matrix` variable.
(Use `matrix` variable till question no 10.)

In [3]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Q.3 select the subset from `matrix`
```python
array([12,13,14,15],
      [17,18,19,20],
      [22,23,24,25])
```

In [5]:
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Q.4 Select the value 20 from the `matrix`

In [8]:
a[3][4]

20

Q.5 Select the below subset.(Use `matrix`)
```python
array([[2],
      [7],
      [12]])
```


In [11]:
a[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

Q.6 Select the below subset. (Use `matrix`)
```python
array([21,22,23,24,25])
```

In [12]:
a[4]

array([21, 22, 23, 24, 25])

Q.7 Select the subset below (Use `matrix`)
```python
array([[16,17,18,19,20],
       [21,22,23,24,25]])
```



In [14]:
a[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Q.8 Get the sum of all the values in `matrix`. (Expected Ans : 325)

In [15]:
a.sum()

325

Q.9 Get the standard deviation of the values in `matrix`(Expected Ans : 7.2111025)

In [16]:
a.std()

7.211102550927978

Q. 10 Get the sum of all the columns in `matrix`. (Expected Ans: array([55,60,65,70,75])

In [17]:
a.sum(axis=0)

array([55, 60, 65, 70, 75])

Q.11 Reverse a 1D array.

In [18]:
a=np.array([1,2,3,4,5])
a[::-1]

array([5, 4, 3, 2, 1])

Q.12 Find indices of non-zero elements from [10,20,0,0,40,0]

In [20]:
b=np.array([10,20,0,0,40,0])
b[b>0]

array([10, 20, 40])

Q.13 Create a 10x10 array with random values and find the minimum and maximum values.

In [26]:
a=np.random.randint(1,100,(10,10))
print(a.min())
a.max()

4


99

Q.14 Create a 10x10 array with 1 on the border and 0 inside.

In [30]:
c=np.ones((8,8),dtype=int)
c[1:-1,1:-1] = 0
c

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

Q. 15 Create 8x8 array and fill it with the cheakerboard pattern.

In [33]:
d=np.zeros((8,8),dtype=int)
d[1::2,::2] = 1
d[::2,1::2] =1
d

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Q.16 Create a numpy array of size 10 with values ranging from 0 to 1, both excluded.

In [39]:
e=np.random.rand(10)
e

array([0.24575511, 0.03101741, 0.68835899, 0.29142193, 0.640142  ,
       0.36635893, 0.76771337, 0.86139842, 0.7070531 , 0.07667167])

Q.17 Create a random array of size 10 and sort it.

In [45]:
f=np.random.randint(1,10,10)
f.sort()
f

array([1, 3, 3, 5, 6, 7, 7, 8, 9, 9])

Q.18 Create a random array of size 10 and replace the maximum value with 0.

In [48]:
h=np.argmax(f)
f[h]=0
f

array([1, 3, 3, 5, 6, 7, 7, 8, 0, 0])

Q.19 Create a random array of size 10 and replace the minimum value with 10.

In [51]:
w=np.random.randint(1,10,10)
k=np.argmin(f)
w[k]=10
w

array([ 8,  6,  4,  4,  6,  6,  1,  8,  7, 10])

Q.20 Create an array of size 5x5 and swap two rows.

In [56]:
q=np.random.randint(1,50,(5,5))
q[2,0]=q[0,2]
q

array([[18, 24, 17, 47, 31],
       [45, 24, 38,  7, 41],
       [17, 25, 19, 39, 17],
       [ 5,  4,  3,  1,  3],
       [ 4, 42, 39, 10, 31]])

# End!