<a href="https://colab.research.google.com/github/Pranav210905/NumPy/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Assignment

---

**Instructions**

1. **Read Each Question Carefully**: Understand what each question is asking before starting.

2. **Complete the Functions**: For each question, you’ll find a partially completed function in the code cell. Fill in the missing parts to complete the function according to the requirements.

3. **Test Your Function**: After completing each function, run the cell to test if your function works correctly.

4. **Answer All Questions**: Ensure you complete all functions. Each question targets different aspects of NumPy.

5. **Download Your Notebook**: Once you’ve finished and tested all functions, download your notebook file (.ipynb) by selecting `File > Download > Download .ipynb`.

6. **Submit Your Work**: Upload the downloaded `.ipynb` file to the designated platform for submission.

7. **Verify Your Submission**: Check that you have submitted the correct file and that it is not corrupted. Resubmit if necessary.

Good luck, and happy coding!

---

In [1]:
# run this code cell
import numpy as np

**1.Create a function desc which takes an ndarray salaries as argument and prints mean, median, variance and standard deviation of salaries** <br>
- Input  : An ndarray of salaries <br>
- Output : mean , median, variance and standard deviation

In [5]:
# Complete this function
def desc(salaries):
  a=salaries.mean()
  b=np.median(salaries)
  c=salaries.var()
  d=salaries.std()
  return a,b,c,d


In [7]:
# Execute this code cell (DO NOT MODIFY)
salaries = np.array([50000,60000,70000,80000,90000,100000])
desc(salaries)

(75000.0, 75000.0, 291666666.6666667, 17078.25127659933)

---
---
**2.Create a function quartiles which takes an ndarray salaries as argument and prints first, second and third quartiles** <br>
- Input  : An ndarray of salaries <br>
- Output : q1, q2 and q3

In [12]:
def quartiles(salaries):
  e= np.quantile(salaries, .50)
  f=np.quantile(salaries, .25)
  g=np.quantile(salaries, .75)
  return e,f,g

In [13]:
salaries = np.array([50000,60000,70000,80000,90000,100000])
quartiles(salaries)

(75000.0, 62500.0, 87500.0)

---
---
**3.Create a function z_scores which takes an ndarray as argument and returns an ndarray having the z scores of all elements** <br>
- Input  : An ndarray of elements <br>
- Output : An ndarray having z scores

In [14]:
def z_scores(nums):
  t=nums.std()
  o=nums.mean()
  p=nums-0
  z_scores=p/t
  return z_scores

In [15]:
nums = np.array([10,20,0,40,50,60])
z_scores(nums)

array([0.46291005, 0.9258201 , 0.        , 1.8516402 , 2.31455025,
       2.7774603 ])

---
---
**4.Create a function variance which takes an ndarray of salaries and returns the variance without using the inbuilt variance function.** <br>
 - Input  : An ndarray
 - Output : variance

In [20]:
def variance(salaries):
  g=salaries.mean()
  m=salaries-g
  u=m**2
  i=u.sum()
  f=salaries.size
  var=i/f
  return var

In [21]:
salaries = np.array([70000,80000,90000,100000,110000])
variance(salaries)

200000000.0

---
---
**5.Create a function comp_salaries which takes an ndarray of salaries and returns all salaries which are higher than the mean salary.** <br>
 - Input  : An ndarray of salaries
 - Output : an ndarray of salaries higher than the mean

In [22]:
def comp_salaries(salaries):
  v=salaries.mean()
  higher_salaries = salaries[salaries>v]
  return higher_salaries

In [23]:
salaries = np.array([76000,69000,40000,58000,85000,92000,94000])
comp_salaries(salaries)

array([76000, 85000, 92000, 94000])

---
---
**6.Create a function cum_sum_diff which takes two ndarrays of same size and returns the difference between cumulative sums at each position.** <br>
- Input  : two ndarrays of having same number of elements
- Output : difference in cumulative sums

In [24]:
def cum_sum_diff(a1, a2):
  y=a1.cumsum()
  z=a2.cumsum()
  diff = y-z
  return diff

In [25]:
a1 = np.array([10,12,14,8,7,9,20])
a2 = np.array([12,11,8,10,9,13,7])
cum_sum_diff(a1,a2)

array([-2, -1,  5,  3,  1, -3, 10])

---
---
**7.Create two ndarrays a1 and a2 each of shape 4,3 using the randint function having integers between 10 to 50 and concatenate them by axis 0.**

In [27]:
a1=np.random.randint(10,50,(4,3))
a2=np.random.randint(10,50,(4,3))
np.concatenate((a1,a2),axis=0)

array([[22, 15, 23],
       [38, 34, 43],
       [29, 43, 27],
       [37, 27, 41],
       [16, 38, 12],
       [18, 10, 45],
       [42, 28, 17],
       [45, 33, 37]])

---
---
**8.Create a function compare which takes two ndarrays as arguments having marks of 2 students in 5 subjects each and prints a list having 5 tuples where each tuple contains the max and min marks recived in each subject.**
- Input  : two ndarrays having 5 integers each
- Output : a list with 5 tuples

- sample:
    - input:
        - student 1 : [80,90,70,75,60]
        - student 2 : [75,92,65,90,95]
    - output:
        - [(80, 75), (92, 90), (70, 65), (90, 75), (95, 60)]

In [49]:
def compare(a1, a2):
  result=[(max(s1,s2),min(s1,s2)) for s1,s2 in zip(a1,a2)]
  return result

In [50]:
student1 = np.array([80,90,70,75,60])
student2 = np.array([75,92,65,90,95])
compare(student1, student2)

[(80, 75), (92, 90), (70, 65), (90, 75), (95, 60)]

---
---
**9.Create a function max_min_pos which takes an ndarray as argument and returns the position of maximum element and minimum element from the ndarray.**
- Input  : An ndarray of integers
- Output : A tuple having index of max and min element

In [51]:
def max_min_pos(nums):
  pos_max=np.argmax(nums)
  pos_min = np.argmin(nums)
  return (pos_max, pos_min)

In [53]:
nums = np.array([80,10,60,40,90,30,20,50])
max_min_pos(nums)

(4, 1)

---
---
**10.Create a function 'between' that takes an ndarray nums and two integers A and B indicating  a range(B > A). The function should return all elements between A and B present in nums.**
- Input : An ndarray having n elements
- Output : Elements between A and B

In [73]:
def between(nums,A,B):
  result= nums[(nums>A) & (nums<B)]
  return result

In [74]:
nums = np.array([10,40,20,30])
between(nums, 15, 35)

array([20, 30])