<a href="https://colab.research.google.com/github/Pranav210905/NumPy/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy




In [7]:
import numpy as np

In [3]:
np_arr = np.arange(1,10000000,1)
np_tenarr=np_arr[:10]
sq_num=np_tenarr ** 2
sq_num

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Creating NdArray

In [4]:
l1=[1,2,3,4,5]
a=np.array(l1)
a

array([1, 2, 3, 4, 5])

In [5]:
t1 = (1,2,3,4,5)
b= np.array(t1)
b

array([1, 2, 3, 4, 5])

In [6]:
c=np.array(range(1,11))

In [8]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
c.shape

(10,)

In [10]:
c.ndim

1

In [12]:
d=np.array([[1,2],[3,4]])
d.ndim

2

In [13]:
d.shape

(2, 2)

In [16]:
a=np.array([1,2,3,4],dtype=float)
a

array([1., 2., 3., 4.])

In [17]:
b=np.array([1.2,3],dtype=int)
b

array([1, 3])

TypeCasting

In [18]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [19]:
a=a.astype(float)
a

array([1., 2., 3., 4., 5.])

In [22]:
a=a.astype(str)
print(a)
a.dtype

['1.0' '2.0' '3.0' '4.0' '5.0']


dtype('<U32')

Creating a ndarray by a range

In [23]:
f=np.arange(10)
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
k=np.arange(1,10,2)

Ones Matrix


In [26]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Zero's Matrix

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [31]:
np.full((4,5),fill_value=6)


array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [33]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

Operations on Numpy Array


In [44]:
h1=np.array([1,2,3,4])
h1+3
h1%3

array([1, 2, 0, 1])

In [45]:
h2=np.array([1,4,8,8])
print(h2+h1)
print(h2*h1)
print(h1/h2)
print(h1%h2)

[ 2  6 11 12]
[ 1  8 24 32]
[1.    0.5   0.375 0.5  ]
[0 2 3 4]


In [46]:
h1**h2

array([    1,    16,  6561, 65536])

In [47]:
h1**h1

array([  1,   4,  27, 256])

In [48]:
h1>3

array([False, False, False,  True])

In [49]:
h1==h2

array([ True, False, False, False])

In [50]:
h1<9

array([ True,  True,  True,  True])

In [51]:
2/h1

array([2.        , 1.        , 0.66666667, 0.5       ])

Indexing and Slicing

In [52]:
g=np.array(range(10))

In [53]:
g[2]

2

In [54]:
g[5]

5

In [55]:
g[9]

9

In [56]:
g[2:9:2]

array([2, 4, 6, 8])

In [57]:
g[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
g[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [62]:
g[-8:-2:3]

array([2, 5])

Reshape and Transpose

In [66]:
l=np.array(range(1,11))

In [73]:
l.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [75]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])