<a href="https://colab.research.google.com/github/Pranav210905/NumPy/blob/main/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Functions


In [ ]:
import numpy as np

In [ ]:
a=np.array([1,4,2,9,3])
a

array([1, 4, 2, 9, 3])

In [ ]:
a.sort()

In [ ]:
s=np.square(a)
s

array([ 1,  4,  9, 16, 81])

In [ ]:
c=np.sqrt(s)
print(c)

[1. 2. 3. 4. 9.]


In [ ]:
f=np.array([1,8,27,])
np.cbrt(f)

array([1., 2., 3., 4.])

In [18]:
g=np.add([1,2,3],[1,2,3])
g

array([2, 4, 6])

In [19]:
g=np.subtract([1,2,3],[1,2,3])
g

array([0, 0, 0])

In [20]:
g=np.multiply([1,2,3],[1,2,3])
g

array([1, 4, 9])

In [22]:
g=np.abs([1,2,3,-1,-2,-3])
g

array([1, 2, 3, 1, 2, 3])

In [25]:
a1=np.array([1,3,5,6,7,4])
a2=np.array([1,5,3,8,5,7])
a1+a2

array([ 2,  8,  8, 14, 12, 11])

In [27]:
np.minimum(a1,a2)

array([1, 3, 3, 6, 5, 4])

In [30]:
np.greater(a2,a1)

array([False,  True, False,  True, False,  True])

In [28]:
np.maximum(a1,a2)

array([1, 5, 5, 8, 7, 7])

In [29]:
np.greater(a1,a2)

array([False, False,  True, False,  True, False])

In [31]:
a1.mean()

4.333333333333333

In [34]:
np.median(a1)

4.5

In [33]:
a1.var()

3.888888888888889

In [35]:
a1.std()

1.9720265943665387

In [36]:
a1.cumsum()

array([ 1,  4,  9, 15, 22, 26])

In [37]:
a1.cumprod()

array([   1,    3,   15,   90,  630, 2520])

In [38]:
a1.min()

1

In [39]:
a2.max()

8

In [40]:
a2.mean()

4.833333333333333

In [42]:
a3=np.arange(64).reshape(8,8)
a3

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [43]:
a3.shape

(8, 8)

In [44]:
c=a3.T
c

array([[ 0,  8, 16, 24, 32, 40, 48, 56],
       [ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63]])

In [45]:
a3.mean()

31.5

In [46]:
a3.mean(axis=0)

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [47]:
a3.mean(axis=1)

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [48]:
a3.std()

18.472953201911167

In [49]:
a3.std(axis=0)

array([18.33030278, 18.33030278, 18.33030278, 18.33030278, 18.33030278,
       18.33030278, 18.33030278, 18.33030278])

In [50]:
a3.std(axis=1)

array([2.29128785, 2.29128785, 2.29128785, 2.29128785, 2.29128785,
       2.29128785, 2.29128785, 2.29128785])

In [51]:
a3.min(axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [52]:
a3.min(axis=1)

array([ 0,  8, 16, 24, 32, 40, 48, 56])

In [53]:
a3.max(axis=0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [54]:
a3.max(axis=1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [55]:
np.argmax(a3)

63

In [57]:
np.argmax(a3,axis=0)

array([7, 7, 7, 7, 7, 7, 7, 7])

In [56]:
np.argmin(a3)

0

In [58]:
np.argmax(a3,axis=1)

array([7, 7, 7, 7, 7, 7, 7, 7])

In [59]:
np.argmin(a3,axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
np.argmin(a3,axis=0)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [63]:
a2.squeeze()

array([1, 5, 3, 8, 5, 7])

In [64]:
a4=np.linspace(1,10,5)
a4

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Importing a library for Determinent,Inverse,Eigen Values


In [69]:
from numpy.linalg import det,inv,eig
a=np.array([1,2,3,4,6,2,4,6,8,2,6,8,3,5,4,6]).reshape(4,4)
a

array([[1, 2, 3, 4],
       [6, 2, 4, 6],
       [8, 2, 6, 8],
       [3, 5, 4, 6]])

In [71]:
det(a)

24.000000000000004

In [72]:
inv(a)

array([[-0.5       , -0.16666667,  0.25      ,  0.16666667],
       [-0.5       , -0.5       ,  0.25      ,  0.5       ],
       [-0.5       , -2.5       ,  1.75      ,  0.5       ],
       [ 1.        ,  2.16666667, -1.5       , -0.66666667]])

In [73]:
eig(a)

EigResult(eigenvalues=array([17.51428744, -2.22006585, -0.94641046,  0.65218887]), eigenvectors=array([[-0.29948437, -0.25600525,  0.09730273,  0.05641088],
       [-0.48028868,  0.5060081 ,  0.46014955, -0.05770171],
       [-0.64671997,  0.63572469,  0.55014119,  0.80873776],
       [-0.51125842, -0.52370912, -0.69002843, -0.58260755]]))

In [77]:
a5=np.array([1,2,3,4,5,7]).reshape(2,3)
a6=np.array([2,5,7,3,4,8]).reshape(2,3)
np.concatenate((a5,a6))

array([[1, 2, 3],
       [4, 5, 7],
       [2, 5, 7],
       [3, 4, 8]])

In [81]:
a7=a5.T
a7

array([[1, 4],
       [2, 5],
       [3, 7]])

In [78]:
np.concatenate((a5,a6),axis=1)

array([[1, 2, 3, 2, 5, 7],
       [4, 5, 7, 3, 4, 8]])

In [79]:
np.concatenate((a5,a6),axis=0)

array([[1, 2, 3],
       [4, 5, 7],
       [2, 5, 7],
       [3, 4, 8]])

Random numbers

In [82]:
a5=np.random.randint(2,6)
a5

4

In [83]:
a5=np.random.randint(2,100,17)
a5

array([24, 69, 78, 86, 52, 91, 24, 97, 79, 87, 84, 96, 91, 10, 51, 69, 76])

In [84]:
a5=np.random.randint(2,100,(10,10))
a5

array([[58, 92, 82, 66, 86, 84, 65, 78, 35, 42],
       [18, 19, 75, 16, 91, 82, 35, 61, 73, 28],
       [86, 83, 50, 53, 98,  2, 37, 99, 28, 61],
       [56, 12, 59, 74, 72, 64, 71, 89, 82, 95],
       [86, 39, 50, 71, 16, 59, 43, 85, 81, 21],
       [ 4, 19, 51, 57, 82, 79, 62, 45, 69, 65],
       [79, 22, 97, 33,  8, 35, 28, 95, 95, 17],
       [70, 83, 81,  3, 14, 33, 36, 75, 24, 75],
       [19, 64, 33, 16, 97, 86, 56, 29, 14, 28],
       [34, 24,  9, 43, 44, 19, 14, 88, 38, 76]])

In [85]:
a5=np.random.rand(8)
a5

array([0.04540033, 0.04381539, 0.62141005, 0.09472969, 0.91298913,
       0.34881178, 0.76861649, 0.76839946])

In [86]:
a5=np.random.randn(8)
a5

array([-1.29154218,  0.17402623,  0.67689844,  1.97022103,  1.23866277,
        0.61137933,  1.63059606,  1.82724194])